// <auto-generated />
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251121153426_AddFirstMigration")]
    partial class AddFirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.HeroBanner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image_One")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image_Three")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image_Two")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text_One")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text_Three")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text_Two")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HeroBanner");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image_One = "construction-workers-sunset.jpg",
                            Image_Three = "working-with-blueprint.jpg",
                            Image_Two = "inspectors-with-sketch.jpg",
                            Text_One = "Your Trusted Partner in Comprehensive Security",
                            Text_Three = "From property protection to event security — we offer a wide range of security services tailored individually to your needs.",
                            Text_Two = "Dependable Cooling\nYou Can Trust — Anytime,\n Anywhere."
                        });
                });

            modelBuilder.Entity("Domain.Entities.KeyWords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArKeyword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnKeyword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KeyWords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArKeyword = "قناع تبريد قابل للارتداء",
                            EnKeyword = "wearable cooling mask"
                        },
                        new
                        {
                            Id = 2,
                            ArKeyword = "حماية من الإجهاد الحراري",
                            EnKeyword = "heat stress protection"
                        },
                        new
                        {
                            Id = 3,
                            ArKeyword = "معدات سلامة العمال",
                            EnKeyword = "outdoor worker safety"
                        },
                        new
                        {
                            Id = 4,
                            ArKeyword = "تقنية التبريد الشخصية",
                            EnKeyword = "personal cooling technology"
                        },
                        new
                        {
                            Id = 5,
                            ArKeyword = "ملابس عملية للطقس الحار",
                            EnKeyword = "sun protection gear"
                        },
                        new
                        {
                            Id = 6,
                            ArKeyword = "تبريد للعمال في الهواء الطلق",
                            EnKeyword = "construction worker cooling"
                        },
                        new
                        {
                            Id = 7,
                            ArKeyword = "حماية من حرارة الشمس",
                            EnKeyword = "smart safety wearables"
                        },
                        new
                        {
                            Id = 8,
                            ArKeyword = "معدات تبريد للعمال",
                            EnKeyword = "agricultural worker protection"
                        },
                        new
                        {
                            Id = 9,
                            ArKeyword = "حلول الحرارة الشديدة",
                            EnKeyword = "security team equipment"
                        },
                        new
                        {
                            Id = 10,
                            ArKeyword = "تتبريد للعمال الزراعيين",
                            EnKeyword = "extreme heat solutions"
                        });
                });

            modelBuilder.Entity("Domain.Entities.MetaPages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArMetaDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArMetaTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArPageTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnMetaDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnMetaTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnPageTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MetaPages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArMetaDescription = "SaVest شركة مبتكرة ملتزمة بتطوير حلول ذكية قابلة للارتداء تُعزز السلامة والراحة في البيئات القاسية. انطلاقًا من فهمها العميق للتحديات التي يواجهها العاملون في الهواء الطلق، تُصمم SaVest منتجات عملية وعالية الأداء مُصممة خصيصًا لتلبية احتياجات العالم الحقيقي.",
                            ArMetaTitle = "الرئيسية",
                            ArPageTitle = "الرئيسية",
                            EnMetaDescription = "SaVest is an innovative company committed to developing smart, wearable solutions that enhance safety and comfort in extreme environments. Born from a deep understanding of the challenges faced by outdoor workers, SaVest designs practical, high-performance products tailored to real-world needs.",
                            EnMetaTitle = "Home",
                            EnPageTitle = "Home",
                            Page = "Home"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Pixels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PixelsApp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PixelsCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pixels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PixelsApp = "Google",
                            PixelsCode = "<script>console.log('Pixels Google');</script>"
                        },
                        new
                        {
                            Id = 2,
                            PixelsApp = "Facebook",
                            PixelsCode = "<script> console.log('Pixels Facebook'); </script>"
                        },
                        new
                        {
                            Id = 3,
                            PixelsApp = "TikTok",
                            PixelsCode = "<script> console.log('Pixels TikTok'); </script>"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
